name: test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true

jobs:
  Test:
    outputs:
      repo_info: ${{steps.set-repo_info.outputs.repo_info}}
    runs-on: ubuntu-latest
    steps:
    # マスクテスト
    - name: test
      run: |
        # echo "::add-mask::${{ github.event.inputs.name }}"
        echo "Access ""${{ github.event.inputs.name }}"
        # 入力値を参照
        # curl ${{ github.event.inputs.name }}
        # シークレット情報を参照
        # curl ${{secrets.SECRET_URL}}
        
        # サマリ出力
        echo -e "# INPUT INFO:" >> $GITHUB_STEP_SUMMARY
        echo -e "| Items  | Info |" >> $GITHUB_STEP_SUMMARY
        echo -e "| - | - |" >> $GITHUB_STEP_SUMMARY
        echo -e "| PROJECT | XXXXX |" >> $GITHUB_STEP_SUMMARY
        echo -e "| COLLECTION | XXXXX |" >> $GITHUB_STEP_SUMMARY
        echo -e "| REPOSITORY(BRANCH OR TAG) | XXXXX |" >> $GITHUB_STEP_SUMMARY

        echo -e "# JIRA TICKET LIST:" >> $GITHUB_STEP_SUMMARY
        echo -e "| Tickets  | Log Info |" >> $GITHUB_STEP_SUMMARY
        echo -e "| - | - |" >> $GITHUB_STEP_SUMMARY
        echo -e "| XXXXX-XXX | Exist |" >> $GITHUB_STEP_SUMMARY
        echo -e "| XXXXX-XXX | Exist |" >> $GITHUB_STEP_SUMMARY
        echo -e "| XXXXX-XXX | Not Exist |" >> $GITHUB_STEP_SUMMARY

        echo -e "# SEARCH RESULT:" >> $GITHUB_STEP_SUMMARY
        echo -e "| Items  | Log Info |" >> $GITHUB_STEP_SUMMARY
        echo -e "| - | - |" >> $GITHUB_STEP_SUMMARY
        echo -e "| TICKET COUNT | XXX |" >> $GITHUB_STEP_SUMMARY
        echo -e "| LOG EXIST TICKET COUNT | XXX |" >> $GITHUB_STEP_SUMMARY
        echo -e "| LOG NOT EXIST TICKET COUNT | XXX |" >> $GITHUB_STEP_SUMMARY
