name: test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true

jobs:
  Test:
    outputs:
      repo_info: ${{steps.set-repo_info.outputs.repo_info}}
    runs-on: ubuntu-latest
    steps:
    # マスクテスト
    - name: test
      run: |
        # echo "Hello!""${{ github.event.inputs.name }}"
        echo "::add-mask::${{ github.event.inputs.name }}"
        # cd /home/ubuntu/work/sekiguchi
        # echo "Hello!""${{ github.event.inputs.name }}"
        curl ${{ github.event.inputs.name }}
