name: test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true

jobs:
  Test:
    outputs:
      repo_info: ${{steps.set-repo_info.outputs.repo_info}}
    runs-on: ubuntu-latest
    steps:
    # マスクテスト
    - name: test
      run: |
        # echo "::add-mask::${{ github.event.inputs.name }}"
        echo "Access ""${{ github.event.inputs.name }}"
        # 入力値を参照
        # curl ${{ github.event.inputs.name }}
        # シークレット情報を参照
        # curl ${{secrets.SECRET_URL}}
        
        # サマリ出力
        #echo "INPUT INFO:" >> $GITHUB_STEP_SUMMARY
        #echo "  PROJECT:XXXXX" >> $GITHUB_STEP_SUMMARY
        #echo "  COLLECTION:XXXXX" >> $GITHUB_STEP_SUMMARY
        #echo "  REPOSITORY(BRANCH OR TAG):XXXXX" >> $GITHUB_STEP_SUMMARY
        #echo "SEARCH RESULT:"  >> $GITHUB_STEP_SUMMARY
        #echo "  JIRA TICKET NO DATA" >> $GITHUB_STEP_SUMMARY

        #echo -e "*INPUT INFO:\n*  PROJECT:XXXXX\n*  COLLECTION:XXXXX\n*  REPOSITORY(BRANCH OR TAG):XXXXX\n*SEARCH RESULT:\n*  JIRA TICKET NO DATA" >> $GITHUB_STEP_SUMMARY

        echo -e "INPUT INFO:\n　PROJECT:XXXXX\n　COLLECTION:XXXXX\n　REPOSITORY(BRANCH OR TAG):XXXXX\nSEARCH RESULT:\n　JIRA TICKET NO DATA" >> $GITHUB_STEP_SUMMARY
