name: test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true

jobs:
  Test:
    outputs:
      repo_info: ${{steps.set-repo_info.outputs.repo_info}}
    runs-on: ubuntu-latest
    steps:
    # マスクテスト
    - name: test
      run: |
        # echo "::add-mask::${{ github.event.inputs.name }}"
        echo "Access ""${{ github.event.inputs.name }}"
        # 入力値を参照
        # curl ${{ github.event.inputs.name }}
        # シークレット情報を参照
        # curl ${{secrets.SECRET_URL}}
        
        # サマリ出力
        echo "# Result:" >> $GITHUB_STEP_SUMMARY
        echo "**JIRA ticket search success.**" >> $GITHUB_STEP_SUMMARY
        
        echo "# INPUT INFO:" >> $GITHUB_STEP_SUMMARY
        echo "| Items  | Info |" >> $GITHUB_STEP_SUMMARY
        echo "| :- | :- |" >> $GITHUB_STEP_SUMMARY
        echo "| PROJECT | XXXXX |" >> $GITHUB_STEP_SUMMARY
        echo "| COLLECTION | XXXXX |" >> $GITHUB_STEP_SUMMARY
        echo "| REPOSITORY(BRANCH OR TAG) | XXXXX |" >> $GITHUB_STEP_SUMMARY

        echo "# JIRA TICKET LIST:" >> $GITHUB_STEP_SUMMARY
        echo "| Tickets  | Log Info |" >> $GITHUB_STEP_SUMMARY
        echo "| :- | :- |" >> $GITHUB_STEP_SUMMARY
        echo "| XXXXX-XXX | Exist |" >> $GITHUB_STEP_SUMMARY
        echo "| XXXXX-XXX | Exist |" >> $GITHUB_STEP_SUMMARY
        echo "| XXXXX-XXX | Not Exist |" >> $GITHUB_STEP_SUMMARY

        echo "# SEARCH RESULT:" >> $GITHUB_STEP_SUMMARY
        echo "| Items  | Count |" >> $GITHUB_STEP_SUMMARY
        echo "| :- | :- |" >> $GITHUB_STEP_SUMMARY
        echo "| TICKET COUNT | XXX |" >> $GITHUB_STEP_SUMMARY
        echo "| LOG EXIST TICKET COUNT | XXX |" >> $GITHUB_STEP_SUMMARY
        echo "| LOG NOT EXIST TICKET COUNT | XXX |" >> $GITHUB_STEP_SUMMARY
